### ISSUE TITLE
Is this up-to-date and working with Jellyfin server?

### ISSUE THREAD

**Issue by Inrego** [jellyfin-archive/jellyfin-apiclient-csharp#3]
Hello.

I see no new commits have been made since forked from the Emby version.
Is that a sign that no api's have changed when comparing to Emby? Or is this project simply a "todo"?

I wanted to know if this api client works, for when I am going to add Jellyfin support to my audiobook app.
If the same api client is used for Emby and Jellyfin, then that makes things a lot easier.
If on the other hand, this project is simply just a todo, and there is no up-to-date C# api client for Jellyfin, then that makes my work a lot harder, since I'd have to make one.

**Comment by dkanada** [comment]
The API client [here](https://github.com/villagra/jellyfin-apiclient-dotnet) is much more active, I would suggest that one.

**Comment by Inrego** [comment]
Yeah I just found that by myself as well. However, it clearly states that it's a work in progress, and not ready for use yet.

**Comment by dkanada** [comment]
I believe @villagra has been using it for his C# client with great success, so it could only be a disclaimer. Maybe he will jump in here and set the record straight, I'm not too sure.

**Comment by jmvillagra** [comment]
Ey... yes. That's the client I'm using for my app. It's not feature complete, but all operations needed in videotape to talk to jellyfin/emby are there. I'll try to add some documentation during the next days explaining how to use it.

**Comment by Inrego** [comment]
I'm not on my way to use it right now. Just doing a bit of research beforehand. I'm looking to make my app ready with Plex first. And then around version 1.0 I'll add Emby and Jellyfin

**Comment by Inrego** [comment]
Also I'm not afraid to step in and add whatever functionality I need to the client. I've had to add a bit to the unofficial Plex client that I was able to find as well.

**Comment by jmvillagra** [comment]
I'll publish the client to nuget soon as well.
btw: thanks for pointing to the plex client, I was looking for it.

**Comment by Inrego** [comment]
There are 2 different C# plex clients in my repositories. I first used https://github.com/Inrego/fa.standard.libraries and added stuff I was missing. But it didn't support connecting to servers you were invited to (only your own). And since plex auth is a not very well documented mess, I looked around and found another rather new client, which supported it. And it's working well so far. It's not feature complete, and I still need to add a few things, I think. https://github.com/Inrego/plex-api
I'll commit my latest changes now. Didn't really think too much about it as I didn't think anyone else was going to use it.

**Comment by Inrego** [comment]
Oh and btw, on the plex-api project, I mostly just added missing models to already support api's, and made the client more subclass-friendly. I then subclass it in my audiobook app and implement the extra functionality there. I don't remember my reasoning for not adding the extra functionality directly in the library, so I guess I'll move it there within the coming days, as it might benefit others.

**Comment by Inrego** [comment]
Moved my changes to the repo now. So now it contains all the customizations/changes that I've made.

**Comment by dkanada** [comment]
@Inrego we like to announce new clients on the official blog, I believe we have a post from @jmvillagra that's going up soon. Let us know when you add support and we can put something on the site.
